# Generated by Django 5.1 on 2024-08-31 16:19

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('logo', models.ImageField(default='review.png', upload_to=pages.models.get_review_upload_path)),
                ('content', models.TextField(max_length=250)),
                ('desginer', models.CharField(max_length=40)),
                ('position', models.CharField(default='Lead Visual Designer at UI8', max_length=40)),
            ],
        ),
    ]
