# Generated by Django 5.1 on 2024-08-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(default='Dorthy Runolfsdottir', max_length=40),
        ),
    ]
