# Generated by Django 5.1 on 2024-08-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='position',
        ),
        migrations.AlterField(
            model_name='review',
            name='desginer',
            field=models.CharField(default='Lead Visual Designer at UI8', max_length=40),
        ),
    ]
