# Generated by Django 5.1 on 2024-08-29 22:10

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Yoga', 'Yoga'), ('Fitness & Gym', 'Fitness & Gym'), ('Gymnastics', 'Gymnastics'), ('Running', 'Running')], default='Yoga', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Fitness', 'Fitness'), ('Mindfulness', 'Mindfulness')], default='Lifestyle', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter class name', max_length=200, unique=True, verbose_name='Class Name')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(default='courses/course_avatar.jpg', upload_to=courses.models.get_image_upload_path)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.category')),
                ('tag', models.ManyToManyField(to='courses.tag')),
            ],
        ),
    ]
