# Generated by Django 5.1 on 2024-08-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_tag_course_tags_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Yoga', 'Yoga'), ('Fitness & Gym', 'Fitness & Gym'), ('Gymnastics', 'Gymnastics'), ('Running', 'Running')], default='Yoga', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Fitness', 'Fitness'), ('Mindfulness', 'Mindfulness')], default='Lifestyle', max_length=50, null=True, unique=True),
        ),
    ]
