# Generated by Django 5.1 on 2024-08-30 18:11

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_tags'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course.jpg', upload_to=courses.models.get_image_upload_path),
        ),
    ]
