# Generated by Django 5.1 on 2024-09-01 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
