# Generated by Django 5.1 on 2024-09-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
