# Generated by Django 5.1 on 2024-09-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(blank=True, default='Sweet and tone', max_length=300, null=True),
        ),
    ]
